apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: clusterstore
spec:
  provider:
    gcpsm:
      projectID: project-id
      auth:
        workloadIdentity:
          clusterLocation: [[[ .region ]]]
          clusterName: [[[ .cluster ]]]
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
