apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: helm-releases
spec:
  interval: 5m
  targetNamespace: [[[ .source_key ]]]
  storageNamespace: [[[ .source_key ]]]
  releaseName: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: "0.5.8"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: helm-releases
      interval: 1m
  values:
    installCRDs: false
    serviceMonitor:
      enabled: true
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: kubernetes-[[[ .env ]]]-[[[ .platform ]]]
