---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- argocd
- cert-manager
- db-operator
- external-secrets
- mongo-atlas-operator
- prometheus-operator
- forecastle
- kong-ingress-controller
